# Generated by Django 3.1.5 on 2021-02-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_admin_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('etkazib berish paytida naqd pul', 'etkazib berish paytida naqd pul'), ('Click', 'Click')], default='etkazib berish paytida naqd pul', max_length=50),
        ),
    ]
