# Generated by Django 3.1.5 on 2021-02-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_auto_20210210_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('etkazib berish paytida naqd pul', 'etkazib berish paytida naqd pul'), ('Click', 'Click'), ('Payme', 'Payme')], default='etkazib berish paytida naqd pul', max_length=50),
        ),
    ]
